DROIDBOOT_GUI_CONFIG_PARSER_LOCAL_PATH := $(GET_LOCAL_DIR)

MODULES +=

OBJS += \
	$(DROIDBOOT_GUI_CONFIG_PARSER_LOCAL_PATH)/droidboot_config.o \
	$(DROIDBOOT_GUI_CONFIG_PARSER_LOCAL_PATH)/droidboot_fs_util.o

