DROIDBOOT_GUI_LIB_LOCAL_PATH := $(GET_LOCAL_DIR)
LVGL_DIR := $(DROIDBOOT_GUI_LIB_LOCAL_PATH)
LVGL_DIR_NAME := lvgl

include $(DROIDBOOT_GUI_LIB_LOCAL_PATH)/ext4/lwext4.mk
include $(DROIDBOOT_GUI_LIB_LOCAL_PATH)/lvgl/lvgl.mk
ifdef OBJS
INCLUDES += $(DROIDBOOT_GUI_LIB_LOCAL_PATH)/lvgl/src
else
GLOBAL_INCLUDES += $(DROIDBOOT_GUI_LIB_LOCAL_PATH)/lvgl/src
endif
