# SPDX-License-Identifier: GPL-2.0+
#

obj-y += droidboot_init.o
obj-y += droidboot_logging.o
obj-y += droidboot_main.o
obj-y += droidboot_screens.o
obj-y += droidboot_helpers.o
obj-y += droidboot_stdfunc.o
obj-y += droidboot_theme.o
